FROM node:20.13.1-alpine

WORKDIR /var/nextjs

# 복사
COPY package.json /var/nextjs
COPY . /var/nextjs

# npm 최신화 및 설치
RUN npm install npm@latest
RUN npm install

# 환경 변수 설정
ARG NODE_ENV=production
ENV NODE_ENV=$NODE_ENV
ENV PORT=5002

# 프로덕션 환경 빌드
RUN npm run build

# 포트 설정
EXPOSE 5002

# 시작 명령어
CMD ["npm", "start"]